/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as ClinicLoginRouteImport } from './routes/clinic.login'
import { Route as ClinicDashboardRouteImport } from './routes/clinic.dashboard'
import { Route as ClinicApplyRouteImport } from './routes/clinic.apply'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicLoginRoute = ClinicLoginRouteImport.update({
  id: '/clinic/login',
  path: '/clinic/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicDashboardRoute = ClinicDashboardRouteImport.update({
  id: '/clinic/dashboard',
  path: '/clinic/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicApplyRoute = ClinicApplyRouteImport.update({
  id: '/clinic/apply',
  path: '/clinic/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/clinics': typeof ClinicsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sos': typeof SosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/apply': typeof ClinicApplyRoute
  '/clinic/dashboard': typeof ClinicDashboardRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/clinics': typeof ClinicsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sos': typeof SosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/apply': typeof ClinicApplyRoute
  '/clinic/dashboard': typeof ClinicDashboardRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/doctors': typeof DoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/clinics': typeof ClinicsRoute
  '/labs': typeof LabsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sos': typeof SosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/apply': typeof ClinicApplyRoute
  '/clinic/dashboard': typeof ClinicDashboardRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/booking-success'
    | '/clinics'
    | '/labs'
    | '/login'
    | '/profile'
    | '/search'
    | '/sos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/apply'
    | '/clinic/dashboard'
    | '/clinic/login'
    | '/doctors/$id'
    | '/hospital/$id'
    | '/staff/dashboard'
    | '/staff/login'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/booking-success'
    | '/clinics'
    | '/labs'
    | '/login'
    | '/profile'
    | '/search'
    | '/sos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/apply'
    | '/clinic/dashboard'
    | '/clinic/login'
    | '/doctors/$id'
    | '/hospital/$id'
    | '/staff/dashboard'
    | '/staff/login'
    | '/doctors'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/booking-success'
    | '/clinics'
    | '/labs'
    | '/login'
    | '/profile'
    | '/search'
    | '/sos'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/apply'
    | '/clinic/dashboard'
    | '/clinic/login'
    | '/doctors/$id'
    | '/hospital/$id'
    | '/staff/dashboard'
    | '/staff/login'
    | '/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ClinicsRoute: typeof ClinicsRoute
  LabsRoute: typeof LabsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SosRoute: typeof SosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ClinicApplyRoute: typeof ClinicApplyRoute
  ClinicDashboardRoute: typeof ClinicDashboardRoute
  ClinicLoginRoute: typeof ClinicLoginRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  HospitalIdRoute: typeof HospitalIdRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/login': {
      id: '/clinic/login'
      path: '/clinic/login'
      fullPath: '/clinic/login'
      preLoaderRoute: typeof ClinicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/dashboard': {
      id: '/clinic/dashboard'
      path: '/clinic/dashboard'
      fullPath: '/clinic/dashboard'
      preLoaderRoute: typeof ClinicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/apply': {
      id: '/clinic/apply'
      path: '/clinic/apply'
      fullPath: '/clinic/apply'
      preLoaderRoute: typeof ClinicApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ClinicsRoute: ClinicsRoute,
  LabsRoute: LabsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SosRoute: SosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ClinicApplyRoute: ClinicApplyRoute,
  ClinicDashboardRoute: ClinicDashboardRoute,
  ClinicLoginRoute: ClinicLoginRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  HospitalIdRoute: HospitalIdRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
